### ISSUE TITLE
"Automatically send age verification when requested" not worked

### ISSUE THREAD

**Issue by Korb** [tfedor/AugmentedSteam#945]
Messages "Content posted in this community may not be appropriate for all ages, or may not be appropriate for viewing at work" are still displayed. Mozilla Firefox 81.0b7 (64-bit), Augmented Steam 1.4.7, Microsoft Windows 10.0.19041.450.

**Comment by MxtOUT** [comment]
Can you see something suspicious in your browser console (F12)?

**Comment by candela97** [comment]
I've seen this happen sometimes in the past as well.
I could reproduce this on workshop items like `https://steamcommunity.com/sharedfiles/filedetails/?id=606009216`, and that was because Steam detached the global header. (The check was added in #833)

**Comment by MxtOUT** [comment]
So you're thinking that this should be fixed?

**Comment by candela97** [comment]
I've tested this on the store and steamcommunity and haven't had any problems.

Although on the develop branch this feature will have to be added to `CSharedFiles` for it to work on direct navigation to workshop items.

**Comment by Korb** [comment]
Still not working. Mozilla Firefox 85.0 (64-bit), Augmented Steam 1.4.8 (31 October 2020)
![2021-01-20_15-58-15](https://user-images.githubusercontent.com/3509797/105178102-a5a0b100-5b38-11eb-9a40-ce40bd730eb3.png)
![2021-01-20_15-58-54](https://user-images.githubusercontent.com/3509797/105178103-a6394780-5b38-11eb-8268-bb86c6dc1720.png)
![2021-01-20_15-59-57](https://user-images.githubusercontent.com/3509797/105178106-a6394780-5b38-11eb-9f26-cdf23a2f28d3.png)
